// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace apiRecuBase.Migrations
{
    [DbContext(typeof(ModeloContext))]
    [Migration("20220215081140_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Influencers.Models.Contrato", b =>
                {
                    b.Property<int>("ContratoId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("InfluencerId")
                        .HasColumnType("int");

                    b.Property<string>("ProductoId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ContratoId");

                    b.HasIndex("InfluencerId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Contrato");
                });

            modelBuilder.Entity("Influencers.Models.Influencer", b =>
                {
                    b.Property<int>("InfluencerId")
                        .HasColumnType("int");

                    b.Property<string>("Manager")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InfluencerId");

                    b.ToTable("Influencer");
                });

            modelBuilder.Entity("Influencers.Models.Producto", b =>
                {
                    b.Property<string>("ProductoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ValorEconomico")
                        .HasColumnType("int");

                    b.HasKey("ProductoId");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Influencers.Models.Contrato", b =>
                {
                    b.HasOne("Influencers.Models.Influencer", "Influencers")
                        .WithMany("Contratos")
                        .HasForeignKey("InfluencerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Influencers.Models.Producto", "Productos")
                        .WithMany("Contratos")
                        .HasForeignKey("ProductoId");

                    b.Navigation("Influencers");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Influencers.Models.Influencer", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("Influencers.Models.Producto", b =>
                {
                    b.Navigation("Contratos");
                });
#pragma warning restore 612, 618
        }
    }
}
